# Generated by Django 5.1.7 on 2025-04-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="zipcode",
            field=models.CharField(max_length=100),
        ),
    ]
