# Generated by Django 5.1.7 on 2025-04-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="state",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
