# Generated by Django 5.1.7 on 2025-04-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_shippingaddress_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
